version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8000:8000
    depends_on:
      - app

  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kluknulo
      - POSTGRES_PASSWORD=kluknulo
      - POSTGRES_DB=kluknulo
    volumes:
      - ./data:/var/lib/postgresql/data