FROM php:8.1-fpm

USER root

RUN apt-get update && apt-get install -y \
      apt-utils \
      libpq-dev \
      libpng-dev \
      libzip-dev \
      zip unzip \
      git && \
      mkdir -p /app && \
      docker-php-ext-install pdo_pgsql && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install gd && \
      docker-php-ext-install zip && \
      apt-get clean \

COPY ./_docker/app/php.ini /usr/local/etc/php/conf.d/php.ini
#COPY /var/www ./
#COPY --chown=${USER}:${USER} ./.docker/web/rootfs /

# Install composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

WORKDIR /var/www

